export enum EmailType {
  ACTIVATION = 'ACTIVATION',
  LEAVE_REQUEST_SUBMITTED = 'LEAVE_REQUEST_SUBMITTED',
  LEAVE_REQUEST_CANCELLED = 'LEAVE_REQUEST_CANCELLED',
  LEAVE_REQUEST_UPDATED = 'LEAVE_REQUEST_UPDATED',
  LEAVE_REQUEST_APPROVED = 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_REJECTED = 'LEAVE_REQUEST_REJECTED',

  OT_PLAN_SUBMITTED = 'OT_PLAN_SUBMITTED',
  OT_PLAN_APPROVED = 'OT_PLAN_APPROVED',
  OT_PLAN_REJECTED = 'OT_PLAN_REJECTED',
  OT_ASSIGNMENT_APPROVED = 'OT_ASSIGNMENT_APPROVED',
  NONE = 'NONE',
}
