export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  LEAVE_OVERLAP = 'LEAVE_OVERLAP',
  CONFLICT_VERSION = 'CONFLICT_VERSION',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
