export enum LeaveType {
    PAID_LEAVE = 'PAID_LEAVE',
    UNPAID_LEAVE = 'UNPAID_LEAVE',
    SICK_LEAVE = 'SICK_LEAVE',
    PARENTAL_LEAVE = 'PARENTAL_LEAVE',
    ANTENATAL_LEAVE = 'ANTENATAL_LEAVE',
    CHILD_MARRIAGE_LEAVE = 'CHILD_MARRIAGE_LEAVE',
    MARRIAGE_LEAVE = 'MARRIAGE_LEAVE',
    BEREAVEMENT_LEAVE = 'BEREAVEMENT_LEAVE',
}