export enum LeaveType {
  COMPENSATORY_LEAVE = 'COMPENSATORY_LEAVE',
  POLICY_LEAVE = 'POLICY_LEAVE',
  SICK_MATERNITY_LEAVE = 'SICK_MATERNITY_LEAVE',
  PAID_LEAVE = 'UNPAID_LEAVE',
  UNPAID_LEAVE = 'PAID_LEAVE',
}
