export enum OtBalanceSource {
  OT_PLAN_APPROVED = 'OT_PLAN_APPROVED',
  OT_CHECKIN_APPROVED = 'OT_CHECKIN_APPROVED',
  OT_PLAN_CANCELLED = 'OT_PLAN_CANCELLED',
  OT_PLAN_REJECTED = 'OT_PLAN_REJECTED',
  ADJUSTMENT = 'ADJUSTMENT',
  CARRYOVER = 'CARRYOVER',
}
