import { UserApprover } from "@/entities/user_approver.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import {User} from "@/entities/users.entity";
import { UserApproverDto } from "../dto/user-approver.dto";
import { AppException } from "@/common";
import { ErrorCode } from "@/common/enums/errror-code.enum";
import { Logger } from "@nestjs/common";

@Injectable()
export class UserApproverService {
  private readonly logger = new Logger(UserApproverService.name);

  constructor(
    @InjectRepository(UserApprover)
    private readonly userApproverRepository: Repository<UserApprover>,
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
  ) {}

  async getApproversForUser(userId: number): Promise<User[]> {
    this.logger.log(`Fetching approvers for user ID: ${userId}`);
  
    const userApprovers = await this.userApproverRepository.find({
      where: { userId, active: true },
      relations: ['approver'],
    });
    return userApprovers.map(ua => ua.approver);
  }

  
  async setApproverForUser(userId: number, dto: UserApproverDto): Promise<UserApprover> {
    this.logger.log(`Setting approver for user ID: ${userId} to approver ID: ${dto.approverId}`);
    this.logger.debug(`Input DTO: ${JSON.stringify(dto)}`);
    
    if(dto.approverId === userId) {
      throw new AppException(ErrorCode.INVALID_INPUT, 'A user cannot be their own approver.', 400);
    }
    const approver = await this.userRepository.findOne({ where: { id: dto.approverId } });
    if (!approver) {
      throw new AppException(ErrorCode.USER_NOT_FOUND, 'Approver user not found.', 404);
    }

    // Deactivate existing approvers
    await this.userApproverRepository.update(
      { userId, active: true },
      { active: false }
    );

    const userApprover = this.userApproverRepository.create({
      userId,
      approverId: dto.approverId,
      createdBy: dto.createdBy,
      active: true,
      // createdAt is auto-generated by @CreateDateColumn
    });
    return this.userApproverRepository.save(userApprover);
  }
}
